### ISSUE TITLE
3D heatmap doesn't seem to work

### ISSUE THREAD

**Issue by atv-axiomatic** [kDanik/heatmap-unity#3]
Hey,

I had to point out 2 separate issues (the first one being the main issue highlighted here):

1.When disabling the "ignore height for color calculations", the particles don't seem to render at all.

2. Also is there a reason why HeatmapController.cs line 103, the if statement checking "eventData.IsCurrentlyDisplayedOnHeatmap" only displays when the eventData is currently on the heatmap? How would the event data be added to the heatmap if it only waited for it to currently be on the heatmap?

**Comment by kDanik** [comment]
Hey,

probably too late to answer, but:

**1.** I tried to set up a new project and use this package there. On my machine, the heatmap works with "ignore height for color calculations" enabled and disabled as expected.

A possible reason for your problems can be the "height of particle system in particles" set to a low number, which makes all your particles to be outside of the box. Try setting it to 0 (to use collider height) or a higher value.

Another thing that you should also check is your "Color Cutoff" setting. Maybe it hides too much or displays too much (with "ignore height for color calculations" disabled you should almost always have "Color Cutoff" with non-zero value.

If you still plan to use this package and the problem is still there, you can open a new issue, with a little bit more details. I would be happy to fix it.

**2.** Fixed, naming was incorrect in EventData class
